server:
  port: 80


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=UTF-8&autoReconnect=TRUE&useSSL=FALSE&serverTimezone=GMT
    password: 12345678


mybatis:
  configuration:
